### ISSUE TITLE
this.errorWithNode is not a function

### ISSUE THREAD

**Issue by abstraktor** [MagicCube/babel-plugin-ui5#2]
## Issue

I have an ES6 class that extends another ES6 class. This issue arises in the line of the super call:

```
TypeError: ...myFile.js: this.errorWithNode is not a function

      at PluginPass.CallExpression (../../../node_modules/babel-plugin-ui5/lib/index.js:117:26)
      at Object.newFn (node_modules/babel-traverse/lib/visitors.js:276:21)
      at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:105:12)
      at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)
      at TraversalContext.visitSingle (node_modules/babel-traverse/lib/context.js:108:19)
      at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:192:19)
      at Function.traverse.node (node_modules/babel-traverse/lib/index.js:114:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:115:19)
```

## Environment

Platform: Windows
Node: v8.5.0
NPM: 5.3.0

extract from my package.json:
```
    "@types/openui5": "^1.40.2",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-eslint": "8.2.5",
    "babel-preset-ui5": "^6.1.0",
```

## Approach
I don't expect you to solve this, just wanted to report it so that other users could find about the state of the project.

**Comment by bogdanmanate** [comment]
I had the same problem and I've solved it by adding export default before the class definition.
e.g. export default class YourClass {}
